name: CI Build

on:
  push:
    branches:
      - master

jobs:
  Build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: pub get
      - name: Build
        run: dart2native ./bin/main.dart -o ./miio
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MIIO_${{ matrix.os }}
          path: ./miio
  BuildWindows:
    name: Build (windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cedx/setup-dart@v2
        with:
          release-channel: dev
      - run: pub get
      - name: Build
        run: dart2native ./bin/main.dart -o ./miio.exe
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: MIIO_windows
          path: ./miio.exe
